### ISSUE TITLE
Change outdated docs about Services and Subscribers

### ISSUE THREAD

**Issue by gorkalaucirica** [BenGor/User#25]
As now we are using message buses we need to explain it in the docs

**Comment by harikt** [comment]
If you are not overwhelmed with questions : What is the alternative to use for `DomainEventPublisher` ? I was looking how to get the events once a command is executed. Is it like register on simple bus bridge ?

**Comment by gorkalaucirica** [comment]
`UserAggregateRoot` stores the events triggered using `publish()`. In case you want to listen to an event you need to create a subscriber, and add it to the command bus event subscribers.

An subscriber example: https://github.com/BenGorUser/User/blob/master/src/BenGorUser/User/Domain/Event/UserInvitedMailerSubscriber.php

We are working to make it easier to add subscribers to the bus for the standalone library, right now the bus building process is quite difficult. Using symfony bundle makes this process easier

**Comment by harikt** [comment]
cool. Thank you for the quick reply. Yes I am looking at the symfony bundle. The problem with that is most of them are tied to interface and can't actually figure out the right dependency it is passing with the symfony/di . I will invest some more time to figure out things.

**Comment by gorkalaucirica** [comment]
Yes... the Dependency Injection login is quite complex for various reasons. The need to generate multiple middleware and the need to generate a bus for each user type. As I told you building the bus is complex, may be interesting for you to check SimpleBus docs: http://simplebus.github.io/MessageBus/

In case is interesting for you, you can check the following branch where we are trying to create a layer of abstraction to create the required buses in the SimpleBusBridge you can check it here https://github.com/BenGorUser/SimpleBusBridge/tree/feature/bus-builder/src/BenGorUser/SimpleBusBridge/Builder

**Comment by harikt** [comment]
Yes I have been trying to read the simple bus, but sometimes I get lost some where. I am not looking it for first time though ;) .

Thank you for the links and help.

**Comment by gorkalaucirica** [comment]
Yes... we had a lot of trouble too... we spent a lot of time trying to understand what happens inside the bus to extend it and we still don`t understand it very well... SimpleBus is technically very well but some more in-detail docs would be very helpfull.

We will check for some alternatives for the bus. We have been reading about https://github.com/prooph these days and looks really good. Maybe we will try to implement this.
