### ISSUE TITLE
Mailers

### ISSUE THREAD

**Issue by harikt** [BenGor/User#27]
Hi, 

I came across this repo accidentally. Nice to see good code.

Thank you for making this open-source to learn some DDD.

But there seems some of the stuffs got changed recently. Eg : https://github.com/BenGorUser/User/blob/85628a911ea53205e5c250975100aef4dca778bb/docs/mailers.md mentions about installing swiftmailer.

But it should go for `composer require bengor-user/swift-mailer-bridge` and other one `mailgun` seems missing. There is another repo https://github.com/flint/Stampie , https://github.com/stof/StampieExtra ( if you have not came across ) that have different implementation other than mailgun.

I hope I can look into more details in the coming days and send a few PR to fix some of the inconsisteny.

Is there any roadmap or some other place where you guys discuss about the same ?

Thank you for your time reading.

**Comment by gorkalaucirica** [comment]
Hi, 

Thanks for your comment.

Those mailer docs are based in 0.5 versión and need a revision before we tag v0.6. 

In v0.5 mailers were located in the infrastructure folder but in v0.6 we moved those implementations to separate packages leaving in this package just basic code.

UserMailer definition will not be changed for v0.6 and will be the same as noted in the docs.

The stampie integration should be developed as a separate package where UserMailer is implemented on top of the library you suggest. We do it in that way to keep our library as independent as we can from 3rd party libraries.

Our roadmap is to write some docs to let other devs play with the whole package ecosystem and once done that we will tag v0.6. If no big issues appear regarding the architecture of this package 1.0 will be tagged

Hope this answers all your questions. More questions are nore than welcome.

**Comment by benatespina** [comment]
@harikt Our plan is to tag the new release today. You are very active in BenGorUser ecosystem so, we want to ask if you see fine for tagging or it is something wrong/missing before to publish new release.

**Comment by harikt** [comment]
@benatespina my policy is release often. So please do go with tagging new releases. We can always make new releases / fixes as soon as they are available.

Thank you so much for asking me my opinion though I have not contributed more into this.
