### ISSUE TITLE
Rename DummyUserPasswordEncoder 

### ISSUE THREAD

**Issue by harikt** [BenGor/User#30]
Hi, 

I was wondering why not rename https://github.com/BenGorUser/User/blob/688647f7f1bc55f97764925e8f31df02e7b5c724/src/BenGorUser/User/Infrastructure/Security/DummyUserPasswordEncoder.php to make use of the password_hash functions in php. That also helps not to write an implementation.

Any thoughts ?

**Comment by benatespina** [comment]
This is a dummy implementation for test purposes, this is not functional implementation. For real use cases we provide a https://github.com/BenGorUser/SymfonySecurityBridge/blob/master/src/BenGorUser/SymfonySecurityBridge/Infrastructure/Security/SymfonyUserPasswordEncoder.php inside SymfonySecurityBridge adapter ;)

**Comment by harikt** [comment]
@benatespina yes I did understood regarding the symfony security bridge. Was wondering if password_hash is also a good use case.

**Comment by benatespina** [comment]
yes, you can make another implementation that calls PHP "password_hash" base function. On the other hand, if you have a look Symfony security component, it is a simple abstraction layer that internally also uses "password_hash"
